import Link from "next/link";

import { requireAdminPage } from "@/lib/auth";
import { listPublishedBlogs } from "@/lib/blogs";
import { listPageSeo } from "@/lib/seo-settings";
import { INDEXABLE_ROUTES, NOINDEX_ROUTES, SITE_URL } from "@/lib/site";

export const dynamic = "force-dynamic";

/**
 * Technical SEO.
 *
 * Read-only on purpose. Vivacity let an admin overwrite public/robots.txt from
 * a textarea; here robots.txt and sitemap.xml are GENERATED from app/robots.ts
 * and app/sitemap.ts, so a hand-edited file would either be ignored or drift
 * out of date the moment a post is published. This screen shows what is being
 * served and where each part comes from.
 */
export default async function TechnicalSeo() {
  await requireAdminPage();

  const [posts, seoPages] = await Promise.all([listPublishedBlogs(), listPageSeo()]);
  const urlCount = INDEXABLE_ROUTES.length + posts.length;

  return (
    <>
      <div className="adm__head">
        <div>
          <h1>Technical SEO</h1>
          <p>What the crawlers are being served right now.</p>
        </div>
        <span style={{ display: "flex", gap: 10 }}>
          <Link
            href="/sitemap.xml"
            target="_blank"
            rel="noreferrer"
            className="adm-btn adm-btn--ghost"
          >
            View sitemap.xml
          </Link>
          <Link
            href="/robots.txt"
            target="_blank"
            rel="noreferrer"
            className="adm-btn adm-btn--ghost"
          >
            View robots.txt
          </Link>
        </span>
      </div>

      <div className="adm-stats">
        <div className="adm-stat">
          <div className="adm-stat__n">{urlCount}</div>
          <div className="adm-stat__l">URLs in the sitemap</div>
        </div>
        <div className="adm-stat">
          <div className="adm-stat__n">{INDEXABLE_ROUTES.length}</div>
          <div className="adm-stat__l">Indexable pages</div>
        </div>
        <div className="adm-stat">
          <div className="adm-stat__n">{posts.length}</div>
          <div className="adm-stat__l">Published posts</div>
        </div>
        <div className="adm-stat">
          <div className="adm-stat__n">{seoPages.length}</div>
          <div className="adm-stat__l">Pages with SEO rows</div>
        </div>
      </div>

      <div className="adm-card">
        <h2 className="adm-card__title">Sitemap</h2>
        <p className="adm-card__hint">
          Generated by <code>app/sitemap.ts</code> and served at{" "}
          <code>{SITE_URL}/sitemap.xml</code>. New posts appear automatically — there is no file
          to upload. Submit that URL once in Google Search Console.
        </p>

        <div className="adm-tablewrap">
          <table className="adm-table">
            <thead>
              <tr>
                <th>Path</th>
                <th>Priority</th>
                <th>Change frequency</th>
              </tr>
            </thead>
            <tbody>
              {INDEXABLE_ROUTES.map((r) => (
                <tr key={r.path}>
                  <td>{r.path}</td>
                  <td>{r.priority}</td>
                  <td style={{ color: "var(--muted)" }}>{r.changeFrequency}</td>
                </tr>
              ))}
              <tr>
                <td>
                  /blogs/…
                  <div className="adm-sub">One entry per published post</div>
                </td>
                <td>0.5</td>
                <td style={{ color: "var(--muted)" }}>yearly</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div className="adm-card">
        <h2 className="adm-card__title">Robots</h2>
        <p className="adm-card__hint">
          Generated by <code>app/robots.ts</code>. Legal pages are excluded from the index
          deliberately, and the sitemap is declared for crawlers that look there first.
        </p>

        <pre
          className="adm-textarea adm-textarea--code"
          style={{ margin: 0, whiteSpace: "pre-wrap" }}
        >
{`User-Agent: *
Allow: /
${NOINDEX_ROUTES.map((r) => `Disallow: ${r}`).join("\n")}

Host: ${SITE_URL}
Sitemap: ${SITE_URL}/sitemap.xml`}
        </pre>

        <p className="adm-hint" style={{ marginTop: 12 }}>
          To change either of these, edit <code>INDEXABLE_ROUTES</code> or{" "}
          <code>NOINDEX_ROUTES</code> in <code>lib/site.ts</code>. They are deliberately not
          editable here: a hand-written robots.txt in <code>public/</code> would sit outside the
          generator and go stale the first time a route moved.
        </p>
      </div>
    </>
  );
}
